coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5
        base: auto
        flags:
          - unit
        paths:
          - "src"
        branches:
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false
        ignore:
          - "src/dkr/didcomm/**/*"
          - "src/dkr/app/cli/**/*"
          - "tests/**/*"