[project]
name = "dkr"
version = "0.0.7"
description = "did:webs DID Method Resolver"
readme = "README.md"
requires-python = ">=3.12.2"
license = {text = "Apache Software License 2.0"}
authors = [
    {name = "Philip S. Feairheller", email = "pfeairheller@gmail.com"}
]
keywords = ["did:webs", "did", "resolver", "webs", "keri", "acdc", "cesr", "vlei"]

dependencies = [
    "aiohttp==3.10.11",
    "lmdb>=1.4.1",
    "pysodium>=0.7.17",
    "blake3>=0.4.1",
    "msgpack>=1.0.8",
    "cbor2>=5.6.2",
    "multidict>=6.0.5",
    "ordered-set>=4.1.0",
    "keri>=1.2.4",
    "hio>=0.6.14",
    "multicommand>=1.0.0",
    "jsonschema>=4.21.1",
    "falcon>=3.1.3",
    "hjson>=3.1.0",
    "PyYaml>=6.0.1",
    "apispec>=6.6.0",
    "mnemonic>=0.21",
    "PrettyTable>=3.10.0",
    "http_sfv>=0.9.9",
    "cryptography==44.0.1",
    "requests>=2.28",
    "simplejson>=3.17.0",
    "tool>=0.8.0",
    "coverage>=7.7.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
"Documentation" = "https://kara.readthedocs.io/"
"Changelog" = "https://kara.readthedocs.io/en/latest/changelog.html"
"Issue Tracker" = "https://github.com/WebOfTrust/kara/issues"

[dependency-groups]
dev = [
    "coverage>=7.7.1",
    "mockito>=1.5.4",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
]
